[package]
name = "screenshots"
version = "0.5.0"
edition = "2021"
description = "A cross-platform screen capturer library"
license = "Apache-2.0"
documentation = "https://docs.rs/screenshots"
homepage = "https://github.com/nashaofu/screenshots-rs"
repository = "https://github.com/nashaofu/screenshots-rs.git"
keywords = ["screenshots", "screenshot", "screen", "capture"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.7"
display-info = {git = "https://github.com/voysys/display-info", tag = "voysys-1"}
anyhow = "1.0.69"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.22.3"

[target.'cfg(target_os="windows")'.dependencies]
fxhash = "0.2.1"
widestring = "1.0.2"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.44.0"
features = ["Win32_Foundation", "Win32_Graphics_Gdi"]

[target.'cfg(target_os="linux")'.dependencies]
dbus = "0.9.7"
xcb = "1.2.0"
